### ISSUE TITLE
Suggest a server-side redirect and HSTS when possible

### ISSUE THREAD

**Issue by jyasskin** [PolymerElements/platinum-https-redirect#1]
In the documentation for this element, can you suggest that folks configure the HTTPS redirect on the server when possible? You can link to https://mozilla.github.io/server-side-tls/ssl-config-generator/ for the HSTS information, but it doesn't have instructions for redirecting yet (https://github.com/mozilla/server-side-tls/issues/87).

**Comment by jyasskin** [comment]
Note that HSTS makes HTTPS sticky, but it doesn't do the redirect in the first place. Folks should also configure their port 80 server to serve a 301 to HTTPS. (HSTS is also a more aggressive step than the redirect since it states that the whole host can handle HTTPS, rather than just the one page that's being redirected.)

@lgarron, what's the right documentation link for HSTS?

**Comment by lgarron** [comment]
> @lgarron, what's the right documentation link for HSTS?

Usually, I think the best place is to link to Wikipedia (which includes links to other important resources).
