### ISSUE TITLE
Consider 0.0.0.0 IP as localhost

### ISSUE THREAD

**Issue by beaufortfrancois** [PolymerElements/platinum-https-redirect#5]
Even though `0.0.0.0` is not a valid IPv4 address, Chrome handles it nicely since https://plus.google.com/+FrancoisBeaufort/posts/EKXw7z1hnqB

It would be kind to not redirect `0.0.0.0` to https and consider it as `localhost` and its siblings.

**Comment by jeffposnick** [comment]
`0.0.0.0` isn't treated as a secure origin, though, and the point of `<platinum-https-redirect>` is to force HTTPS whenever you're not on a secure origin:

![image](https://cloud.githubusercontent.com/assets/1749548/10138913/94d47a88-65ce-11e5-808a-89582134efb3.png)

I'm assuming that Chrome won't whitelist `0.0.0.0` as a secure origin, but if it does, we can revisit.

**Comment by beaufortfrancois** [comment]
I've filed https://code.google.com/p/chromium/issues/detail?id=537540 to treat `0.0.0.0` as a secure origin. If it gets approved (and I'm not sure it will), I'll reopen this ;)
